# Generated by Django 4.2.20 on 2025-04-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_approved_alter_blogpost_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
