# Generated by Django 4.2.20 on 2025-04-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_featured_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="post_type",
            field=models.CharField(
                choices=[("blog", "Blog"), ("recipe", "Recipe")],
                default="blog",
                max_length=10,
            ),
        ),
    ]
