# Generated by Django 4.2.20 on 2025-04-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_remove_userprofile_profile_picture"),
        ("checkout", "0003_alter_order_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name="order",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="userprofile.userprofile",
            ),
        ),
    ]
