# Generated by Django 4.2.20 on 2025-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_alter_order_order_total_alter_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price_at_purchase",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
