# Generated by Django 4.2.20 on 2025-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0007_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bag",
            field=models.TextField(default=""),
        ),
    ]
