# Generated by Django 4.2.20 on 2025-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0008_order_bag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(default="", max_length=254),
        ),
    ]
