# Generated by Django 4.2.20 on 2025-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0009_alter_order_stripe_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("unfulfilled", "Unfulfilled"), ("fulfilled", "Fulfilled")],
                default="unfulfilled",
                max_length=20,
            ),
        ),
    ]
