# Generated by Django 4.2.17 on 2026-02-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0004_alter_userprofile_postcode_and_more"),
        ("checkout", "0011_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_pid", models.CharField(max_length=254, unique=True)),
                ("order_data", models.JSONField()),
                ("items", models.JSONField()),
                ("save_info", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_drafts",
                        to="userprofile.userprofile",
                    ),
                ),
            ],
        ),
    ]
