# Generated by Django 4.2.20 on 2025-04-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_userprofile_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
    ]
