# Generated by Django 4.2.20 on 2025-03-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="has_discount",
            field=models.BooleanField(default=False),
        ),
    ]
