# Generated by Django 4.2.20 on 2025-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_has_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="friendly_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
