# Generated by Django 4.2.20 on 2025-04-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_productreview_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
