# Generated by Django 4.2.20 on 2025-04-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="has_discount",
        ),
    ]
