# Generated by Django 4.2.17 on 2026-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_has_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='product_thumbnails/'),
        ),
    ]
